wandb_version: 1

lr:
  desc: null
  value: 5.0e-05
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701978169.91698
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.16.1
      6: 4.35.2
      8:
      - 4
      - 5
      13: darwin-arm64
